// Code generated by Icestudio 0.2.4-dev
// Sun, 18 Dec 2016 18:38:52 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns


module main_tb 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 10;
 
 // Input/Output
 reg input_clk;
 wire output_led1;
 wire output_led2;
 wire output_led3;
 wire output_ledA;
 wire output_ledB;
 
 // Module instance
 main MAIN (
  .v348220(input_clk),
  .vf59f0c(output_led1),
  .ve5b810(output_led2),
  .v82d849(output_led3),
  .vf89e19(output_ledA),
  .vea8ca5(output_ledB)
 );
 
 // Clock signal
 always #0.5 input_clk = ~input_clk;
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. input_value = 1;
  // e.g. #2 input_value = 0;
  input_clk = 0;
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
